version: '3.8'

services:
  beraxis_landing:
    container_name: beraxis_landing
    image: beraxis_landing:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - general_network

networks:
  general_network:
    external: true
